@startuml control

package "Control" {

  package "sim_round" {
  [step] <-- Mod: accesses
  [draw] <-- Mod: accesses
  }
  [draw] --> Graphics

  package "Graphics" {
    package "App" {
      [new]
      [close]
      [start] --> sim_round: runs
    }
    App --> opengl
    [start] as start_fn
    start_fn --> App
  }
  note left of sim_round: "loops"
}


package "Mod" {

}

package "opengl" {

}

@enduml